[package]
name = "runc"
version = "0.2.0"
authors = ["Yuna Tomida <ytomida.mmm@gmail.com>", "The containerd Authors"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/containerd/rust-extensions"
keywords = ["containerd", "containers", "runc"]
description = "A crate for consuming the runc binary in your Rust applications"
homepage = "https://containerd.io"

[features]
async = ["tokio", "async-trait", "futures", "tokio-pipe"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
libc = "0.2.112"
log = "0.4.14"
nix = "0.25"
oci-spec = "0.5.4"
path-absolutize = "3.0.11"
rand = "0.8.4"
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.74"
tempfile = "3.3.0"
thiserror = "1.0.30"
time = { version = "0.3.7", features = ["serde", "std"] }
uuid = { version = "1.0.0", features = ["v4"] }
os_pipe = "1.0.0"

# Async dependencies
tokio = { version = "1.15.0", features = ["full"], optional = true }
async-trait = { version = "0.1.52", optional = true }
futures = { version = "0.3.19", optional = true }
tokio-pipe = {version="0.2.10", optional = true }
