[package]
name = "containerd-snapshots"
version = "0.1.0"
authors = ["Maksym Pavlenko <pavlenko.maksym@gmail.com>", "The containerd Authors"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/containerd/rust-extensions"
homepage = "https://containerd.io"
keywords = ["containerd", "server", "grpc", "containers"]
categories = ["api-bindings", "asynchronous"]
description = "Remote snapshotter extension for containerd"

[dependencies]
thiserror = "1.0"
tonic = "0.6"
prost = "0.9"
prost-types = "0.9"
tokio = { version = "1.15", features = ["sync"] }
tokio-stream = "0.1.8"

[dev-dependencies]
log = "0.4"
async-stream = "0.3.2"
futures = "0.3.17"
simple_logger = { version  = "1.13", default-features = false }

[build-dependencies]
tonic-build = "0.6"
