name: Coverage
on:
  push:
    branches: "main"
  pull_request:
    branches: "main"

jobs:
  coverage:
    name: Collect
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      statuses: write

    steps:
      - uses: actions/checkout@v4

      - run: |
          sudo apt-get install protobuf-compiler

      - name: Install grcov
        run: |
          cargo install --locked grcov
          grcov --version

      - name: Tests
        env:
          RUSTFLAGS: "-Cinstrument-coverage"
          LLVM_PROFILE_FILE: "target/coverage/%p-%m.profraw"
        run: |
          sudo -E $(command -v cargo) test --all-features

          # Fix permissions after sudo.
          sudo chown -R $(whoami) target/coverage/

      - name: Collect coverage data
        run: |
          grcov . \
            --source-dir . \
            --binary-path ./target/debug/ \
            --branch \
            --ignore-not-existing \
            --output-types markdown,lcov \
            --keep-only 'crates/*' \
            --output-path ./target/coverage/

      - name: Upload coverage data
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          files: ./target/coverage/lcov
          verbose: true

      - name: Publish job summary
        run: |
          echo "# Coverage" >> $GITHUB_STEP_SUMMARY
          cat target/coverage/markdown.md >> $GITHUB_STEP_SUMMARY
